### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by belucid** [ring-clojure/ring-mock#13]
There's no LICENSE.md file for the specified MIT license. More and more OSS tools are scanning for these and concluding ring-mock doesn't have a specified license.

**Comment by weavejester** [comment]
Does it matter, considering every Clojure-aware tool will report the license correctly?

**Comment by belucid** [comment]
Well, I brought it up because VersionEye is a Clojure aware tool and it reports it as license unknown.

**Comment by weavejester** [comment]
It's not Clojure-aware if it doesn't check the project or build file for the license.

I'll consider adding a license file for generic tools, but adding license files for all the repositories I'm involved in is going to take a while, and it's not currently high priority for me.

**Comment by weavejester** [comment]
Fixed by 88a4715d
