### ISSUE TITLE
What is `json-body`

### ISSUE THREAD

**Issue by cloojure** [ring-clojure/ring-mock#20]
Hi - In the 3rd example, I am not sure what the function `json-body` is doing:

 (is (= (your-handler (-> (mock/request :post "/api/endpoint")
                           (json-body {:foo "bar"})))

**Comment by Atsman** [comment]
@cloojure check sources, it serializes map to json string, passes it to request and sets content-type

@weavejester  why is it not released to clojars?

**Comment by weavejester** [comment]
@Atsman I'm afraid I've been busy, and Ring-Mock hasn't been high on my todo list.

**Comment by Atsman** [comment]
@weavejester i copy pasted some code because of that :(

**Comment by weavejester** [comment]
0.3.2 deployed, API documentation updated.

**Comment by Atsman** [comment]
you are the best 🥇
