### ISSUE TITLE
post  form-params bug

### ISSUE THREAD

**Issue by xingzhefeng** [ring-clojure/ring-mock#21]
:content-type "application/x-www-form-urlencoded",
must in 
:headers {"cookie" "ring-session=testuser"  "content-type" "application/x-www-form-urlencoded; charset=UTF-8"}

**Comment by weavejester** [comment]
Sorry, I don't understand. Are you saying that the `:content-type` key is missing from the constructed request map? Because the `:content-type` key is deprecated, and has been for some time.
