### ISSUE TITLE
What's the right way to simulate file upload

### ISSUE THREAD

**Issue by erez-rabih** [ring-clojure/ring-mock#9]
Hi,

I'm currently simulating file upload via the following CURL command:

```
curl -v  -XPOST -F filedata=@my_file.png localhost:3000/upload_endpoint
```

I want to simulate file uploads in tests but setting the Content-Type header with boundaries and a proper body like HTTP multipart spec requires is kind of tiresome.

Is there a good way to simulate file uploads via ring-mock?

Thanks in advance.

**Comment by weavejester** [comment]
Ring-Mock doesn't have a function to simulate a multipart upload, but you could record a multipart stream as a byte array or generate one with the Apache Commons File Upload library.

**Comment by pimeys** [comment]
Did you have any luck with this? Trying to write the same functionality and here I am:

```clojure
(defn do-request
  "A wrapper to add headers map to the request"
  ([verb headers path]
   (reduce (fn [req h] (mock/header req (key h) (val h)))
           (mock/request verb path)
           headers))
  ([verb headers path body]
   (mock/body (mock/header (do-request verb headers path) "content-type" "application/json") body)))

(defn send-file [verb headers path file-path]
  (let [file (IOUtils/toByteArray (io/input-stream file-path))
        file-header (str/join "\r\n" ["--kulli"
                                      "Content-Disposition: form-data; name=\"file\"; filename=\"test-file.p12\""
                                      "Content-Type: application/octet-stream"
                                      ""])
        file-footer (str/join "\r\n" ["" "--kulli--"])
        data (byte-array (mapcat seq [file-header file file-footer]))
        all-headers (assoc headers
                          "Content-Type" "multipart/form-data; boundary=kulli"
                          "Content-Length" (count file))]
    (mock/body (do-request verb all-headers path) data)))
```

But my file is nil when the request arrives to compojure routes...

**Comment by jeroenvandijk** [comment]
@pimeys @erez-rabih I just came across this, I believe you can use [peridot](https://github.com/xeqi/peridot) (based on ring-mock) for testing file uploads

**Comment by erez-rabih** [comment]
@jeroenvandijk Thanks for the update I will have a look at it

**Comment by danielcompton** [comment]
A quick example of how this looks using ring-mock for any other searchers: 

```clojure
(-> (ring.mock.request/request :post "/my-file-upload")
    (merge (peridot.multipart/build {:data (io/file (io/resource "data.csv"))}))
    (app))
```

**Comment by Macroz** [comment]
Wouldn't it be nice to have this as a core feature?

**Comment by hoxu** [comment]
@weavejester could this be reopened? Would be nice if someone had time to make a PR with this functionality.

**Comment by weavejester** [comment]
@hoxu Just open a new issue. This is issue is a question, rather than a feature request.
